<?php

/**
 * @file
 * Contains elastic_appsearch.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\elastic_appsearch\Entity\Server;
use Drupal\Core\Render\Element;
use Drupal\Core\Url ;

/*
 * Load all theme functions.
 */
require_once __DIR__ . '/elastic_appsearch.theme.inc';


/**
 * Implements hook_help().
 */
function elastic_appsearch_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the elastic_appsearch module.
    case 'help.page.elastic_appsearch':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal module to interact with elastic app search.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme().
 */
function elastic_appsearch_theme() {
  return [
    'elastic_appsearch_admin_fields_table' => [
      'render element' => 'element',
    ],
    'engine' => [
      'variables' => [
        'engine' => NULL,
        'server_count' => NULL,
        'server_count_error' => NULL,
        'index_process' => NULL,
        'description' => NULL,
        'table' => NULL,
        'form' => NULL
      ],
    ]
    ];
}


// /**
//  * Implements hook_entity_operation().
//  */
// function elastic_appsearch_entity_operation_alter(array &$operations, $entity) {
//   $entityTypeId = $entity->getEntityTypeId();
  
//   if ($entityTypeId !== 'server') {
//     return;
//   }

//   // print_r($operations); exit;
//   $enigines = Url::fromRoute('entity.engine.collection', ['server'=>$entity->id()]);
//   $operations['engines'] = array(
//       'title' => t('Engines'),
//       'weight' => 20,
//       'url' => $enigines,
//   );
// }